second_app/personal_portfolio/blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>', views.detail, name='detail')
    ]

second_app/personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skill import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

second_app/personal_portfolio/blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

second_app/personal_portfolio/skill/models.py
from django.db import models


class Skill(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='skill/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title


class Test(models.Model):
    ti1 = models.CharField(max_length=200)
    ti2 = models.CharField(max_length=200)

second_app/personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

second_app/personal_portfolio/skill/views.py
from django.shortcuts import render
from .models import Skill, Test


def index(request):
    projects = Skill.objects.all()
    return render(request, 'skill/index.html', {'projects': projects})


def test(request):
    # test = Test.objects.all()
    return render(request, 'skill/test.html')

second_app/personal_portfolio/blog/templates/blog/blogs.html
{% extends 'skill/base.html' %}
{% load static %}
{% block content %}
<h1>Блог</h1>
<h2 class="count">Постов: {{blogs.count}}</h2>
{% for blog in blogs %}
<div class="element">
    <h2 class="top"><a href="{% url 'blog:detail' blog.id %}">{{blog.title}}</a></h2>
    <div class="blog_text">
        <h5>{{blog.date|date:'j E Y'}}</h5>
        <p>{{blog.description|striptags|truncatechars:360}}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

second_app/personal_portfolio/blog/templates/blog/detail.html
{% extends 'skill/base.html' %}
{% load static %}
{% block content %}

<div class="detail">
    <h1>{{blog.title}}</h1>
    <h2>{{blog.date|date:'j E Y'}}</h2>
    {{blog.description|safe}}
</div>

{% endblock %}

second_app/personal_portfolio/blog/templates/blog/test.html
{% extends 'skill/base.html' %}
{% load static %}
{% block content %}
<h1>Блог</h1>

{% for blog in test %}

        <h5>{{blog}}</h5>
        <p>{{blog}}</p>

{% endfor %}
{% endblock %}

second_app/personal_portfolio/skill/templates/skill/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="icon" type="image/x-icon" href="{% static 'skill/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="menu">
    <div class="wrap">
        <div class="logo">
            <a href="{% url 'index'%}"><img src="{% static 'skill/logo.png'%}" alt=""></a>
        </div>
        <ul>
            <li><a href="{% url 'index'%}">Главная</a></li>
            <li><a href="{% url 'blog:blogs'%}">Блог</a></li>
            <li><a href="{% static 'skill/resume.pdf'%}" target="_blank">Резюме</a></li>
        </ul>
    </div>
</div>
    <div class="content">
        <div class="wrap">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

second_app/personal_portfolio/skill/templates/skill/index.html
{% extends 'skill/base.html' %}
{% load static %}
{% block content %}
<h1>Портфолио разработчика</h1>
<div class="img">
    <img src="{% static 'skill/wc.jpg'%}">
</div>
<h2>Стек технологий</h2>
<div class="block">
    {% for p in projects %}
    <div class="element">
        <div class="img"><img src="{{p.image.url}}" alt=""></div>
        <div class="text">
            <h2><a href="{{p.url}}" target="_blank">{{p.title}}</a></h2>
            <p>{{p.description}}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

second_app/personal_portfolio/skill/templates/skill/test.html
{% extends 'skill/base.html' %}
{% load static %}
{% block content %}
<h1>Блог</h1>

{% for blog in test %}

        <h5>{{blog}}</h5>
        <p>{{blog}}</p>

{% endfor %}
{% endblock %}